### ISSUE TITLE
Valid SQL Query is rejected

### ISSUE THREAD

**Issue by barry1955** [thebuggenie/b2db#5]
Hi,
I've just tried to update The Buggenie from 3.2.7 to 4.0 on the way to 4.1 (the straight through upgrade failed).

I am currently getting an error on navigating to the page as follows

An error occurred in The Bug Genie
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'listtypes listtypes0 LEFT JOIN scopes scopes1 ON (scopes1.id=lis' at line 1
An exception was thrown in the B2DB framework
"
SQL:

SELECT listtypes0.name AS listtypes0_name, listtypes0.itemtype AS listtypes0_itemtype, listtypes0.itemdata AS listtypes0_itemdata, listtypes0.sort_order AS listtypes0_sort_order, listtypes0.key AS listtypes0_key, listtypes0.scope AS listtypes0_scope, listtypes0.id AS listtypes0_id, scopes1.name AS scopes1_name, scopes1.description AS scopes1_description, scopes1.enabled AS scopes1_enabled, scopes1.uploads_enabled AS scopes1_uploads_enabled, scopes1.max_upload_limit AS scopes1_max_upload_limit, scopes1.custom_workflows_enabled AS scopes1_custom_workflows_enabled, scopes1.max_workflows AS scopes1_max_workflows, scopes1.max_users AS scopes1_max_users, scopes1.max_projects AS scopes1_max_projects, scopes1.max_teams AS scopes1_max_teams, scopes1.id AS scopes1_id, scopes2.name AS scopes2_name, scopes2.description AS scopes2_description, scopes2.enabled AS scopes2_enabled, scopes2.uploads_enabled AS scopes2_uploads_enabled, scopes2.max_upload_limit AS scopes2_max_upload_limit, scopes2.custom_workflows_enabled AS scopes2_custom_workflows_enabled, scopes2.max_workflows AS scopes2_max_workflows, scopes2.max_users AS scopes2_max_users, scopes2.max_projects AS scopes2_max_projects, scopes2.max_teams AS scopes2_max_teams, scopes2.id AS scopes2_id FROM listtypes listtypes0 LEFT JOIN scopes scopes1 ON (scopes1.id=listtypes0.scope) LEFT JOIN scopes scopes2 ON (scopes2.id=listtypes0.scope) WHERE (listtypes0.itemtype = 'status') "

But this query is valid and works when I copy it to say phpmyadmin.  I get results as expected.  

This error seems to be in B2DB.

Thanks for help.
 Barry

**Comment by zegenie** [comment]
Which mysql version is this?

**Comment by barry1955** [comment]
Hi
Server version: 5.5.47-0ubuntu0.14.04.1 (Ubuntu)

Sorry, I haven't had time to get back to find exactly where it dies.  

I have to get some python scripts running (urgent they said).

Thanks for the interest, I'll try to post something about my investigations in the next few days.

(I have wriiten 0 lines of python)

**Comment by barry1955** [comment]
I've been investigating in detail:

The error is shown in doSelect (in ..[path to]/thebuggenie/vendor/thebuggenie/b2db/src/Table.php

I added the following lines:
`

        	echo "</pre>";
		var_dump(array( "sql query string "=>  $crit->sql,
                               ));
             	die( __FILE__." :: ".__LINE__."</pre>");	
            $statement = Statement::getPreparedStatement($crit);


`
I get this printed out :
array (size=1)
  'sql query string ' => string 'SELECT listtypes0.name AS listtypes0_name, listtypes0.itemtype AS listtypes0_itemtype, listtypes0.itemdata AS listtypes0_itemdata, listtypes0.sort_order AS listtypes0_sort_order, listtypes0.key AS listtypes0_key, listtypes0.scope AS listtypes0_scope, listtypes0.id AS listtypes0_id, scopes1.name AS scopes1_name, scopes1.description AS scopes1_description, scopes1.enabled AS scopes1_enabled, scopes1.uploads_enabled AS scopes1_uploads_enabled, scopes1.max_upload_limit AS scopes1_max_upload_limit, scopes1.custo'... (length=1451)

/usr/share/thebuggenie/vendor/thebuggenie/b2db/src/Table.php :: 399

It seems that the generated query string has reached a limit of some sort.

It's very odd that when I got the origin al message, it SQL string was not trimmed - I ran it.

I'll need to look more deeply, but this is quite disturbing.  I found 2 copies of Table.php one in  B2DB and one in vendor/b2db
This upgrade had been dragging on for ages now.

**Comment by barry1955** [comment]
I've traced further in TGB/vendor/thebuggenie/src/Statement.php

'
             $res = $this->statement->execute($values);

	         echo "</pre>";
		 echo "<br> Full SQL Query <br>";
		 echo $this->statement->queryString;
		 echo "<br><hr><br>";
'
The query string in full is :+1: 

`SELECT listtypes0.name AS listtypes0_name, listtypes0.itemtype AS listtypes0_itemtype, listtypes0.itemdata AS listtypes0_itemdata, listtypes0.sort_order AS listtypes0_sort_order, listtypes0.key AS listtypes0_key, listtypes0.scope AS listtypes0_scope, listtypes0.id AS listtypes0_id, scopes1.name AS scopes1_name, scopes1.description AS scopes1_description, scopes1.enabled AS scopes1_enabled, scopes1.uploads_enabled AS scopes1_uploads_enabled, scopes1.max_upload_limit AS scopes1_max_upload_limit, scopes1.custom_workflows_enabled AS scopes1_custom_workflows_enabled, scopes1.max_workflows AS scopes1_max_workflows, scopes1.max_users AS scopes1_max_users, scopes1.max_projects AS scopes1_max_projects, scopes1.max_teams AS scopes1_max_teams, scopes1.id AS scopes1_id, scopes2.name AS scopes2_name, scopes2.description AS scopes2_description, scopes2.enabled AS scopes2_enabled, scopes2.uploads_enabled AS scopes2_uploads_enabled, scopes2.max_upload_limit AS scopes2_max_upload_limit, scopes2.custom_workflows_enabled AS scopes2_custom_workflows_enabled, scopes2.max_workflows AS scopes2_max_workflows, scopes2.max_users AS scopes2_max_users, scopes2.max_projects AS scopes2_max_projects, scopes2.max_teams AS scopes2_max_teams, scopes2.id AS scopes2_id FROM listtypes listtypes0 LEFT JOIN scopes scopes1 ON (scopes1.id=listtypes0.scope) LEFT JOIN scopes scopes2 ON (scopes2.id=listtypes0.scope) WHERE (listtypes0.itemtype = ?)`

the Values pased are" 
 ' 'Values' => 
    array (size=1)
      0 => string 'status' (length=6) 
.

I'm stumped for now.  

I'll have to come back to this  - the company is still running on 3.2.7  Could this be a bug in PDO?

I'll test the query string in a spearate php file later.

**Comment by barry1955** [comment]
I've moved the Query into a simple php file to test if the issue is in PDO.

I used the Statement::execute() method with both a parametrised  query and with a string with the 'status' added into the string.

Both work??

I get all the answers I expect.

Still do not know why this query fails when wrapped in more code.

**Comment by zegenie** [comment]
If it wasn't for the fact that it's an *actual* mysql error message, I would suspect that the error was occurring somewhere else in the code and only actually trapped in an sql code execution exception handler. But the error message originates from mysql, which goes against that assumption.

Another thing you could try is to turn on mysql query logging and try to find the offending query to compare it against the output generated by b2db. While the query should be identical, the parameter binding in pdo might make the actual query different to the output generated in php.

**Comment by barry1955** [comment]
Hi, I have been on other things (again) hopefully I can test the whole thing on some updated platforms. The server is was running on has old versions of everything I think.

**Comment by barry1955** [comment]
Hi,
Finally got back to this.

I've upgraded all the suporting components (Ubuntu, mysql, PHP ) and I'm starting again.

I think we can close this.

**Comment by barry1955** [comment]
I just noticed that mysql workbench complained about listtype0.key, though it runs.  using lissttypes0.`key` works as well.  More soon.  I'm taking a break from writing a report.
